version: "3"

services:

    mongodb:
      build:
        context:
        dockerfile: .Dockerfile
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongodb/mongodb_data:/data/db
      restart: unless-stopped
      environment:
        MONGO_INITDB_DATABASE: dbadmin
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

